# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a077f0eeba2f81469c41b3be21395406fda91e10e923cab94eb6f85fb6eb610fb520dac6eff1d133d75838c487d2b0ba9df5c288a686c1d7aa69302353ae1cc8

test:
  secret_key_base: 8572fa6ac28cdb14ab401bbc62f07bbe39502044c4bb5206a35365f3fe89ec97f388f93af4f0aba3ae6799c5ab3cda220f041e867184b31bfd003343a796e90a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
